title: Ten-42 Traffic Control
theme: jekyll-theme-minimal
logo: /assets/img/test-logo.png
description: by Scott Brown

navigation_show: true
navigation_title: Navigation
navigation_items:
  - title: About
    url: about.html